/**
 * Builds preview.html from the real front end.
 *
 *   npm run build:preview            rewrite preview.html
 *   npm run build:preview -- --check fail if preview.html is out of date
 *
 * The preview runs the production stylesheet and application script unchanged
 * against an in-browser mock API, so the screens and handlers being previewed
 * are the same ones that get deployed. Editing preview.html by hand would let
 * the two drift apart; edit public/ instead and rebuild.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'preview.html');
const checkOnly = process.argv.includes('--check');

const read = (relative) => fs.readFile(path.join(root, relative), 'utf8');

const [styles, mock, app, pkg, logo] = await Promise.all([
  read('public/styles.css'),
  read('public/preview-mock.js'),
  read('public/app.js'),
  read('package.json'),
  fs.readFile(path.join(root, 'public/logo.webp')),
]);

const version = JSON.parse(pkg).version;
// preview.html is a single file people open from disk or a share link, so the
// logo travels with it rather than being fetched from a server that isn't there.
const logoDataUri = `data:image/webp;base64,${logo.toString('base64')}`;

// Guard against a closing script tag appearing inside the inlined sources.
for (const [name, source] of [['preview-mock.js', mock], ['app.js', app]]) {
  if (/<\/script/i.test(source)) {
    console.error(`${name} contains a literal </script sequence, which cannot be inlined safely.`);
    process.exit(1);
  }
}

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#50AF37">
<title>Gaeilgeoir Guides Operational Preview V${version.split('.')[0]}</title>
<!-- Generated by scripts/build-preview.js. Edit public/styles.css, public/preview-mock.js
     and public/app.js, then run: npm run build:preview -->
<style>
${styles.trim()}
</style>
</head>
<body>
<div id="app"><div class="boot-screen"><div class="brand-lockup large"><img class="brand-logo" src="${logoDataUri}" alt="Gaeilgeoir Guides"><span class="brand-sub">Homework<br>Portal</span></div><div class="spinner"></div></div></div>
<div id="toast-root" aria-live="polite"></div>
<div id="modal-root"></div>
<script>
window.__GG_LOGO__ = ${JSON.stringify(logoDataUri)};
${mock.trim()}
</script>
<script>
${app.trim()}
</script>
</body>
</html>
`;

if (checkOnly) {
  const current = await fs.readFile(target, 'utf8').catch(() => '');
  if (current !== html) {
    console.error('preview.html is out of date. Run: npm run build:preview');
    process.exit(1);
  }
  console.log('preview.html is up to date.');
} else {
  await fs.writeFile(target, html);
  console.log(`Built preview.html (${(html.length / 1024).toFixed(0)} KB) from public/styles.css, public/preview-mock.js and public/app.js.`);
}
